### PR TITLE
Adds update:show event to  CTabs

### PR DESCRIPTION
**Pull request by CVeniamin**
Currently there is no event that indicate the click on a CTab. 
This PR adds a `update:show` event for `CTabs` indicating `index` of new active `CTab`.  

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch (or to a previous version branch), _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by woothu** [comment]
What are real-life applications for tracking tab click?

**Comment by CVeniamin** [comment]
I have a tab with a `vue2-google-maps` component and I can only obtain the reference to that component after the component is rendered, i.e.,  it became an active tab. 
This issue is caused by the `v-if` condition which `vue2-google-maps` component does not play nicely. Basically, using `update:show` event I track when the component can be accessed by its ref.

Still new to vue and it is possible I'm doing something wrong?

**Comment by woothu** [comment]
Interesting case

Accessing component by reference is considered bad practice because it generates tight coupling without a trace, is error-prone and hard to debug. Why do you need a reference? Can you share your code?

**Comment by CVeniamin** [comment]
The concrete example that I'm trying to achieve is to `panTo` a specific location.
This example is also shown in the [vue-google-maps](https://github.com/xkjyeah/vue-google-maps) package.

```html
<template>
<GmapMap ref="mapRef" ...>
</GmapMap>
</template>
<script>
export default {
  mounted () {
    // At this point, the child GmapMap has been mounted, but
    // its map has not been initialized.
    // Therefore we need to write mapRef.$mapPromise.then(() => ...)

    this.$refs.mapRef.$mapPromise.then((map) => {
      map.panTo({lat: 1.38, lng: 103.80})
    })
  }
}
```
In this case accessing the reference is necessary in order to have access to Google Maps API.

**Comment by woothu** [comment]
This example doesn't show an edge case, which couldn't be done by props. It just shows how to make access by ref (because it is not standard due to the promise). 

Behavior showed in the example can be achieved by the 'center' prop:
```html
<GmapMap
  :center="{lat:10, lng:10}"
  :zoom="7"
  map-type-id="terrain"
  style="width: 500px; height: 300px"
>
 [...]
```
If you ever encounter similar problem you can use watch for ref change (https://jsfiddle.net/kenberkeley/9pn1uqam/). But this is the last thing you want to do, as its as hacky as CTabs component :P 

Anyway, I see this functionality, as something which might have possible applications i.e. saving tabs state. But still, it doesn't really solve this component flexibility problem. What if users would like to invoke events on tabs for some reason? We could think of solution that solves all these problems but it would demand a change of this component API. For now, it sacrifices full flexibility for convenient API (CTab are fake components allowing making one component for tab instead of two).

I will merge your request and make some changes to it so it will emit an event on tab change, not on tab click.

**Comment by CVeniamin** [comment]
@woothu, thank you for the feedback! 

Indeed, I could use `:center` instead of `panTo` but I also use `fitTo` and `fitBounds` and `panToBounds`  to zoom-in into a specific area in the map but it is not relevant.

I picked `update:show` event after seeing it being used in other components, next time I will take into consideration the naming. 
You are correct tab change is much better than tab click.

**Pull request merged**
